### ISSUE TITLE
Best way to install 

### ISSUE THREAD

**Issue by 2016rshah** [Shrugs/asdfghjkl#1]
I want to use this EVERY DAY FOR EVERYTHING on my macbook pro. What is the best way to install it? Thanks!

**Comment by shrugs** [comment]
Thanks to our cutting edge implementation, everything _Just Works_ <sup>:tm:</sup> .

Just download the project and run it as root. If anything doesn't work, it's _definitely_ not our fault.

---

Actually though, it _should_ work. There may be some swift language updates necessary to get it to compile, but it worked last time I ran it (tbh, like 1 month ago).

**Comment by kp666** [comment]
is it possible to run this in linux?

**Comment by shrugs** [comment]
@kp666 This code definitely won't work on linux; it uses a lot of OSX-specific code and functions. That said, intercepting keyboard events and moving the pointer is also popular on linux, most likely using some X functions like `XWarpPointer`. Good luck!
